set(Boost_INCLUDE_DIR
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/accumulators/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/algorithm/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/align/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/any/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/array/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/asio/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/assert/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/assign/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/atomic/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/bimap/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/bind/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/chrono/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/chrono/stopwatches/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/circular_buffer/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/compatibility/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/compute/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/concept_check/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/config/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/container/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/context/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/conversion/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/convert/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/core/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/coroutine/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/coroutine2/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/crc/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/date_time/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/detail/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/disjoint_sets/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/dll/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/dynamic_bitset/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/endian/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/exception/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/fiber/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/filesystem/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/flyweight/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/foreach/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/format/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/function/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/function_types/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/functional/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/fusion/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/fusion/include/boost/fusion/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/geometry/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/gil/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/graph/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/graph_parallel/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/hana/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/heap/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/icl/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/integer/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/interprocess/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/intrusive/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/io/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/iostreams/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/iterator/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/lambda/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/lexical_cast/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/local_function/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/locale/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/lockfree/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/log/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/logic/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/math/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/metaparse/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/move/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/mpi/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/mpl/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/mpl/preprocessed/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/msm/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/multi_array/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/multi_index/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/multiprecision/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/numeric/conversion/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/numeric/interval/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/numeric/odeint/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/numeric/ublas/IDEs/qtcreator/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/numeric/ublas/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/optional/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/parameter/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/phoenix/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/phoenix/test/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/polygon/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/pool/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/predef/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/preprocessor/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/program_options/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/property_map/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/property_tree/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/proto/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/ptr_container/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/python/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/qvm/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/random/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/range/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/ratio/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/rational/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/regex/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/scope_exit/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/serialization/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/signals/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/signals2/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/smart_ptr/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/sort/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/spirit/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/spirit/include/boost/spirit/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/spirit/include/boost/spirit/repository/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/statechart/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/static_assert/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/system/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/test/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/thread/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/throw_exception/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/timer/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/tokenizer/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/tr1/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/tti/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/tuple/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/type_erasure/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/type_index/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/type_traits/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/typeof/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/units/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/unordered/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/utility/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/uuid/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/variant/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/vmd/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/wave/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/winapi/include
    ${CMAKE_CURRENT_LIST_DIR}/../external/boost/libs/xpressive/include
)
